flags: {}
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/opt/libffi/lib
extra-include-dirs:
- /usr/local/opt/llvm/include
packages:
- '.'
system-ghc: true
extra-deps:
- llvm-hs-4.0.1.0
- llvm-hs-pure-4.0.0.0
resolver: lts-8.18
